[package]
name = "mapper"
version = "0.1.0"
authors = ["Axylos <robertdraketalley@gmail.com>"]
edition = "2018"

[dependencies]
drakey-fuse = "0.4.2-alpha"
time = "*"
libc = "*"
log = "*"
syslog = "*"
serde_json = "*"
