[package]
name = "mapper"
version = "0.1.0"
authors = ["Axylos <robertdraketalley@gmail.com>"]
edition = "2018"

[dependencies]
fuse = { path = "../rust-fuse" }
reqwest = "0.9.19"
time = "*"
libc = "*"
log = "*"
syslog = "*"
serde_json = "*"
